<center><font color=#555555><font size=5> B.Eng Financial Engineering </font> <br> <br> <br> <br>

<center><font color=#555555><font size=6> F.E. Diego Alberto López Lazareno </font> <br> <br>
   
<center> <font color= #555555> <font size = 4> Feb 2022 </a> | <font color= #555555> <font size = 4> Repository: <a href='https://github.com/diegolazareno/Cloning_Superinvestors'>Link</a></font>

<hr style="border:0.02in solid gray"> </hr>

<center> <font color= #555555> <font size = 6> Cloning Superinvestors </font> <br> <br> <font color= #555555> <font size = 5> Shameless Cloning Portfolio </font>
    
![](https://images.squarespace-cdn.com/content/v1/568cf1da4bf1182258ed49cc/1465332485460-3NMTZQF96HB91VBPMNMA/Screen+Shot+2016-06-08+at+6.45.27+AM.png?format=2500w)

<hr style="border:0.02in solid gray"> </hr>

<br>

<font color= #555555> <font size = 4> Abstract </font>

<font color= #6B6B6B> <font size = 3> The trades of different value investors are cloned. Even with the information delay good performance is obtained. 
 </font>

<br>

# <font color= #6B6B6B> <font size = 6> 1. Introduction </font>

<hr style="border:0.02in solid gray"> </hr>

This project aims to clone the operations of different recognized value investors in order to evaluate their performance. This can be achieved since the information of the quarterly operations of investors such as Warren Buffett, Charlie Munger or David Tepper are disclosed to the public through the $13$-F filings. However, it should be clarified that such operations, which only include the purchase and sale of shares, will be carried out with a delay of $45$ days, since this is the period that must pass from the end of any quarter for the information to be revealed. The ultimate goal of the project is to answer the following question: **can good returns be obtained by cloning the operations of superinvestors even when the information arrives with a certain delay?**

*NOTE: the necessary information is obtained from DATORAMA.* 

![](https://www.azquotes.com/picture-quotes/quote-i-believe-in-the-discipline-of-mastering-the-best-that-other-people-have-ever-figured-charlie-munger-59-5-0528.jpg)

## Assumptions

+ All the information regarding the operations of the investors arrives with a delay of $45$ days after the end of each quarter, consequently the purchase/sale of shares is executed with a delay of that amount of time. 
+ There is no initial capital, since it is intended to quantify the returns that would be obtained if the superinvestor's operations were cloned. 
+ Shares are only purchased when the superinvestor allocates capital for the first time (no further capital is added to such positions). Something similar happens with sales, since the position in the assets is only sold when the superinvestor gets rid of his complete stake (positions are not partially reduced either). 
+ Transaction costs are not considered.

<br>

# <font color= #6B6B6B> 1. Li-Lu </font>

Li Lu is a Chinese-born American value investor, businessman and philanthropist. He is the founder and chairman of Himalaya Capital Management. Prior to emigrating to America, he was one of the student leaders of the 1989 Tiananmen Square student protests. In 2021, he also co-founded The Asian American Foundation and serves as its chairman (Wikipedia).

![](https://static.gurufocus.com/1405596037812412416.jpg)

<hr style="border:0.02in solid gray"> </hr>

In [1]:
# Required libraries
import data
import functions
import pandas as pd
pd.set_option("display.max_rows", None, "display.max_columns", None)

## <font color= #6B6B6B> 1.1 Li Lu's Activity </font>

Below is information regarding the historical operations of the superinvestor in question. Such operations include the purchase/sale of financial assets, which are reported quarterly.

In [2]:
filepath = "files/Superinvestors.xlsx"
datan = data.readData(filepath, "Li Lu")
superInvestor, dates = functions.dataWrangling(datan)

datan.head(10)

,History,Stock,Activity,Share change,% change to portfolio
0,Q4 2021,NaN,NaN,NaN,NaN
1,≡,FB - Meta Platforms Inc.,Add 53.02%,303600.0,3.83
2,≡,BAC - Bank of America Corp.,Add 18.03%,2228000.0,3.72
3,≡,PDD - Pinduoduo Inc.,Sell 100.00%,363165.0,1.53
4,Q3 2021,NaN,NaN,NaN,NaN
5,≡,BRK.B - Berkshire Hathaway CL B,Buy,897749.0,11.41
6,Q1 2021,NaN,NaN,NaN,NaN
7,≡,FB - Meta Platforms Inc.,Reduce 40.37%,387700.0,5.78
8,Q4 2020,NaN,NaN,NaN,NaN
9,≡,AAPL - Apple Inc.,Buy,759600.0,5.55

In [3]:
datan.tail(10)

,History,Stock,Activity,Share change,% change to portfolio
13,≡,FB - Meta Platforms Inc.,Add 118.59%,722100.0,14.42
14,≡,MU - Micron Technology Inc.,Add 15.81%,1567100.0,5.61
15,Q2 2020,NaN,NaN,NaN,NaN
16,≡,FB - Meta Platforms Inc.,Buy,608900.0,13.00
17,≡,GOOG - Alphabet Inc. CL C,Buy,85900.0,11.42
18,≡,BABA - Alibaba Group Holdings,Sell 100.00%,175000.0,4.77
19,Q1 2020,NaN,NaN,NaN,NaN
20,≡,MU - Micron Technology Inc.,Add 26.81%,2095000.0,12.36
21,≡,BAC - Bank of America Corp.,Buy,12358987.0,36.79
22,≡,BABA - Alibaba Group Holdings,Buy,175000.0,4.77

## <font color= #6B6B6B> 1.2 Li Lu's Shameless Cloning </font>

For each cloned operation the following is displayed: 

+ **Ticker**. It is the stock's ticker symbol. 
+ **Timestamp (Buy)**. It is the date on which the purchase operation was carried out (considering the information delay).
+ **Buy Price**. Is the purchase price.
+ **Timestamp (Sell)**. It is the date on which the sale operation was carried out (considering the information delay).
+ **Sell Price**. Is the sale price.
+ **Effective Return %**. It is the total return obtained by the operation (in percentage).
+ **CAGR %**. It is the annualized return on investment (in percentage).

In [4]:
cloning = functions.superInvestorCloning(superInvestor, dates)
cloning

,Ticker,Timestamp (Buy),Buy Price,Timestamp (Sell),Sell Price,Effective Return %,CAGR %
0,BAC,2020-05-15 00:00:00,20.616364,2022-02-19 20:27:33.195590,45.959999,122.929708,56.432252
1,BABA,2020-05-15 00:00:00,203.679993,2020-08-14 00:00:00,253.970001,24.690696,139.399763
2,FB,2020-08-14 00:00:00,261.23999,2022-02-19 20:27:33.868825,206.160004,-21.084056,-14.261545
3,GOOG,2020-08-14 00:00:00,1507.72998,2022-02-19 20:27:34.323464,2609.350098,73.064815,42.821211
4,AAPL,2021-02-14 00:00:00,132.403061,2022-02-19 20:27:34.759564,167.300003,26.356598,25.56021
5,PDD,2021-02-14 00:00:00,202.809998,2022-02-14 00:00:00,59.16,-70.82984,-70.333357
6,BRK-B,2021-11-14 00:00:00,284.670013,2022-02-19 20:27:35.527749,314.799988,10.584176,45.264513

## <font color= #6B6B6B> 1.3 Li Lu's Shameless Cloning Performance </font>

Finally, some performance metrics are shown.

In [5]:
functions.metrics(cloning)

   Mean Effective Return % Mean CAGR %  Mean Holding Period (Years)
0                23.673157   56.432252                     1.061905

## <font color= #6B6B6B> 1.4 Comments </font>

In the case of Li Lu, there is little data on its operations, which date back to just a couple of years ago. However, it seems that his focused investment style does pay off, even when his trades are cloned with a data lag.

<br>

# <font color= #6B6B6B> 2. Bill Ackman </font>

William Albert Ackman is an American investor and hedge fund manager. He is the founder and CEO of Pershing Square Capital Management, a hedge fund management company. His investment approach makes him an activist investor (Wikipedia).

![](https://i.insider.com/5ec402492618b955cc3107f3?format=jpeg)

<hr style="border:0.02in solid gray"> </hr>

## <font color= #6B6B6B> 2.1 Bill Ackman's Activity </font>

In [6]:
datan = data.readData(filepath, "Bill Ackman")
superInvestor, dates = functions.dataWrangling(datan)

datan.head(10)

,History,Stock,Activity,Share change,% change to portfolio
0,Q4 2021,NaN,NaN,NaN,NaN
1,≡,HLT - Hilton Worldwide Holdings,Reduce 2.26%,291018.0,0.43
2,Q3 2021,NaN,NaN,NaN,NaN
3,≡,CMG - Chipotle Mexican Grill Inc.,Add 2.63%,28589.0,0.55
4,≡,DPZ - Dominos Pizza Inc.,Add 2.60%,53032.0,0.27
5,≡,HHC - Howard Hughes Corp.,Add 1.11%,150156.0,0.14
6,≡,QSR - Restaurant Brands International,Add 1.01%,240331.0,0.16
7,≡,HLT - Hilton Worldwide Holdings,Add 0.98%,125307.0,0.17
8,≡,LOW - Lowe's Cos.,Add 0.95%,95951.0,0.21
9,≡,A - Agilent Technologies,Sell 100.00%,11695838.0,16.14

In [7]:
datan.tail(10)

,History,Stock,Activity,Share change,% change to portfolio
236,≡,CP - Canadian Pacific Railway,Buy,20201175.0,3.23
237,≡,GLRE - Greenlight Capital Re Ltd.,Sell 100.00%,250000.0,0.10
238,Q2 2011,NaN,NaN,NaN,NaN
239,≡,FDO - Family Dollar Stores,Add 92.47%,5330306.0,4.38
240,≡,C - Citigroup Inc.,Add 60.32%,8849963.0,5.76
241,≡,JCP - Penney (J.C.),Add 10.87%,3796500.0,2.05
242,≡,FO - Fortune Brands Inc.,Add 3.01%,501397.0,0.50
243,≡,GGP - Genl Growth Properties,Add 0.60%,430859.0,0.11
244,≡,MDLZ - Mondelez International,Reduce 0.04%,8276.0,0.00
245,≡,CXW - CoreCivic Inc.,Sell 100.00%,4417100.0,1.94

## <font color= #6B6B6B> 2.2 Bill Ackman's Shameless Cloning </font>

In [8]:
cloning = functions.superInvestorCloning(superInvestor, dates)
cloning

1 Failed download:
- BKW: No data found for this date range, symbol may be delisted

,Ticker,Timestamp (Buy),Buy Price,Timestamp (Sell),Sell Price,Effective Return %,CAGR %
0,LOW,2011-11-14 00:00:00,19.660484,2012-02-14 00:00:00,22.868275,16.315928,80.654589
1,CP,2011-11-14 00:00:00,11.058598,2016-11-14 00:00:00,27.093884,145.002889,19.31196
2,BEAM,2012-02-14 00:00:00,18.75,2014-08-14 00:00:00,18.75,0.0,0.0
3,FBHS,2012-02-14 00:00:00,17.703674,2012-08-14 00:00:00,21.01639,18.712023,40.395168
4,PG,2012-08-14 00:00:00,50.320118,2022-02-19 20:28:01.274293,159.899994,217.765539,12.720227
5,MATX,2012-11-14 00:00:00,17.724953,2013-11-14 00:00:00,20.795506,17.323334,17.066848
6,MDLZ,2013-02-14 00:00:00,22.249083,2013-08-14 00:00:00,26.810995,20.503823,44.912755
7,APD,2013-08-14 00:00:00,77.701965,2017-08-14 00:00:00,132.164505,70.091586,13.983441
8,ZTS,2014-11-14 00:00:00,41.121742,2017-02-14 00:00:00,53.376907,29.802154,12.086221
9,QSR,2015-02-14 00:00:00,35.392536,2022-02-19 20:28:01.984842,57.049999,61.192176,6.93872
10,BHC,2015-05-15 00:00:00,224.630005,2017-05-15 00:00:00,14.17,-93.691849,-74.356311
11,ACT,2015-05-15 00:00:00,19.388964,2015-08-14 00:00:00,19.388964,0.0,0.0
12,MDLZ,2015-11-14 00:00:00,38.772549,2018-11-14 00:00:00,40.762592,5.13261,1.657643
13,NOMD,2016-05-15 00:00:00,8.27,2017-11-14 00:00:00,14.64,77.025387,45.526828
14,CMG,2016-11-14 00:00:00,414.179993,2022-02-19 20:28:02.522820,1523.319946,267.791775,27.610066
15,ADP,2017-08-14 00:00:00,99.76017,2019-11-14 00:00:00,162.116669,62.506408,23.69497
16,NKE,2018-02-14 00:00:00,65.377274,2018-05-15 00:00:00,67.060974,2.575361,10.706268
17,RTX,2018-05-15 00:00:00,71.551208,2019-08-14 00:00:00,73.442413,2.643149,2.080952
18,LOW,2018-08-14 00:00:00,92.708984,2022-02-19 20:28:03.083708,222.690002,140.20326,27.826626
19,HLT,2019-02-14 00:00:00,79.517357,2022-02-19 20:28:03.658072,150.410004,89.153676,23.171902
20,SBUX,2019-02-14 00:00:00,67.031189,2021-05-15 00:00:00,109.520981,63.388092,24.020917
21,BRK-B,2019-08-14 00:00:00,195.809998,2020-08-14 00:00:00,210.960007,7.737097,7.605555
22,A,2019-11-14 00:00:00,75.573082,2021-11-14 00:00:00,157.572464,108.503425,43.600386
23,BX,2020-05-15 00:00:00,47.913738,2020-08-14 00:00:00,49.817688,3.973703,16.667572
24,PK,2020-05-15 00:00:00,7.31,2020-08-14 00:00:00,9.46,29.411766,177.314855
25,DPZ,2021-05-15 00:00:00,430.412994,2022-02-19 20:28:04.091521,435.619995,1.209768,1.558097

## <font color= #6B6B6B> 2.3 Bill Ackman's Shameless Cloning Performance </font>

In [9]:
functions.metrics(cloning)

   Mean Effective Return % Mean CAGR %  Mean Holding Period (Years)
0                52.472042   80.654589                      2.39359

## <font color= #6B6B6B> 2.4 Comments </font>

Bill Ackman is a great investor, this is proven by the incredible sustained returns that his active investment strategy generates.

<br>

# <font color= #6B6B6B> 3. Mohnish Pabrai </font>

Mohnish Pabrai is an Indian-American businessman, investor, and philanthropist. He was born in Bombay (Mumbai), India (Wikipedia).

![](https://pbs.twimg.com/profile_images/1427939070777249796/XsFELlON_400x400.jpg)

<hr style="border:0.02in solid gray"> </hr>

## <font color= #6B6B6B> 3.1 Mohnish Pabrai's Activity </font>

In [10]:
datan = data.readData(filepath, "Mohnish Pabrai")
superInvestor, dates = functions.dataWrangling(datan)

datan.head(10)

,History,Stock,Activity,Share change,% change to portfolio
0,Q4 2021,NaN,NaN,NaN,NaN
1,≡,MU - Micron Technology Inc.,Add 15.49%,244662.0,10.52
2,≡,SRG - Seritage Growth Properties,Reduce 25.59%,1211000.0,7.42
3,≡,BABA - Alibaba Group Holdings,Sell 100.00%,57347.0,4.45
4,Q3 2021,NaN,NaN,NaN,NaN
5,≡,MU - Micron Technology Inc.,Add 1.75%,27150.0,1.01
6,≡,BABA - Alibaba Group Holdings,Reduce 77.83%,201374.0,15.63
7,Q2 2021,NaN,NaN,NaN,NaN
8,≡,BABA - Alibaba Group Holdings,Add 53.23%,89878.0,7.34
9,Q1 2021,NaN,NaN,NaN,NaN

In [11]:
datan.tail(10)

,History,Stock,Activity,Share change,% change to portfolio
332,≡,WFC - Wells Fargo,Buy,371001.0,3.89
333,≡,HNR - Harvest Natural Resources Inc.,Reduce 0.32%,4500.0,0.04
334,≡,PNCL - Pinnacle Airlines Corp.,Reduce 0.69%,19000.0,0.02
335,≡,POT - Potash Corp. of Saskatchewan Inc.,Reduce 1.89%,8910.0,0.18
336,≡,FRFHF - Fairfax Financial Holdings Ltd.,Reduce 20.64%,11969.0,2.29
337,≡,ZINC - Horsehead Holding Corp.,Reduce 21.87%,382636.0,1.55
338,≡,SHLDQ - Sears Holdings Corp.,Reduce 83.61%,351946.0,11.83
339,≡,BRK.A - Berkshire Hathaway CL A,Reduce 93.75%,15.0,0.90
340,≡,CCRT - CompuCredit Holdings Corp.,Sell 100.00%,324152.0,1.29
341,≡,CRYP - CryptoLogic Ltd.,Sell 100.00%,144695.0,0.24

## <font color= #6B6B6B> 3.2 Mohnish Pabrai's Shameless Cloning </font>

In [12]:
cloning = functions.superInvestorCloning(superInvestor, dates)
cloning

1 Failed download:
- BPO: No data found for this date range, symbol may be delisted

1 Failed download:
- HNR: No data found for this date range, symbol may be delisted

1 Failed download:
- DTV: No data found, symbol may be delisted

1 Failed download:
- NXEO: No data found, symbol may be delisted

1 Failed download:
- NXEOU: No data found, symbol may be delisted

,Ticker,Timestamp (Buy),Buy Price,Timestamp (Sell),Sell Price,Effective Return %,CAGR %
0,WFC,2009-05-15 00:00:00,18.016754,2012-05-15 00:00:00,24.339884,35.095831,10.385388
1,TEX,2009-08-14 00:00:00,14.028885,2011-08-14 00:00:00,16.097662,14.746554,7.018941
2,IBKR,2009-11-14 00:00:00,13.669878,2010-08-14 00:00:00,12.829739,-6.145917,-8.024002
3,CSE,2010-02-14 00:00:00,5.16,2012-08-14 00:00:00,7.1,37.596901,13.426346
4,ICO,2010-05-15 00:00:00,24.48,2011-08-14 00:00:00,24.48,0.0,0.0
5,PKX,2010-11-14 00:00:00,97.080559,2012-02-14 00:00:00,89.340683,-7.972632,-6.335341
6,TECK,2010-11-14 00:00:00,39.660404,2011-05-15 00:00:00,37.823975,-4.630385,-8.951545
7,BIP,2011-02-14 00:00:00,8.44802,2012-02-14 00:00:00,11.398144,34.92089,34.368445
8,BRP,2011-08-14 00:00:00,16.370001,2012-05-15 00:00:00,16.370001,0.0,0.0
9,BAC,2011-11-14 00:00:00,5.22482,2015-05-15 00:00:00,14.407546,175.752026,33.072948
10,TEX,2012-02-14 00:00:00,21.740618,2012-08-14 00:00:00,19.570246,-9.983028,-18.781931
11,C,2012-02-14 00:00:00,27.429796,2015-08-14 00:00:00,49.469517,80.34956,18.086864
12,GM,2012-08-14 00:00:00,15.62018,2013-05-15 00:00:00,24.9722,59.871398,85.237121
13,CHK,2012-08-14 00:00:00,44.074036,2014-11-14 00:00:00,44.074036,0.0,0.0
14,BRK-B,2014-05-15 00:00:00,126.360001,2015-05-15 00:00:00,145.259995,14.95726,14.737964
15,GM,2014-05-15 00:00:00,26.792402,2015-05-15 00:00:00,28.164875,5.122619,5.050704
16,PKX,2014-08-14 00:00:00,81.839996,2016-02-14 00:00:00,39.400002,-51.857278,-38.081081
17,STLA,2015-02-14 00:00:00,6.960757,2020-08-14 00:00:00,9.725208,39.714803,6.179207
18,GOOG,2015-02-14 00:00:00,541.353699,2018-05-15 00:00:00,1079.22998,99.357644,23.296561
19,BRK-B,2016-02-14 00:00:00,128.559998,2017-02-14 00:00:00,166.949997,29.861543,29.30646
20,RACE,2016-05-15 00:00:00,41.478302,2018-11-14 00:00:00,108.509018,161.604291,46.109766
21,SRG,2016-05-15 00:00:00,42.917297,2017-08-14 00:00:00,45.603687,6.259457,4.909912
22,AER,2016-08-14 00:00:00,38.41,2018-05-15 00:00:00,55.59,44.727936,23.154997
23,LUV,2016-11-14 00:00:00,43.637268,2018-05-15 00:00:00,50.37051,15.430027,9.904177
24,MU,2019-02-14 00:00:00,42.126137,2022-02-19 20:28:43.399051,90.800003,115.543152,28.545688
25,EAF,2019-08-14 00:00:00,10.374752,2020-05-15 00:00:00,5.817293,-43.928369,-53.10981
26,SRG,2020-08-14 00:00:00,12.72,2022-02-19 20:28:44.052924,9.11,-28.380507,-19.49989
27,BABA,2021-05-15 00:00:00,211.050003,2022-02-14 00:00:00,121.919998,-42.2317,-51.243783

## <font color= #6B6B6B> 3.3 Mohnish Pabrai's Shameless Cloning Performance </font>

In [13]:
functions.metrics(cloning)

   Mean Effective Return % Mean CAGR %  Mean Holding Period (Years)
0                27.706503   10.385388                     1.803373

## <font color= #6B6B6B> 3.4 Comments </font>

Mohnish Pabrai is the investor who inspired this project and, as expected, it is worthwhile to clone his trades.

# <font color= #6B6B6B> 4. Michael Burry </font>

Michael James Burry is an American investor, hedge fund manager, and physician. He founded the hedge fund Scion Capital, which he ran from $2000$ until $2008$, before closing it to focus on his personal investments. He is best known for being amongst the first investors to predict and profit from the subprime mortgage crisis that occurred between $2007$ and $2010$ (Wikipedia).

![](https://s03.s3c.es/imag/_v0/770x420/6/9/c/michael-burry-770.png)

<hr style="border:0.02in solid gray"> </hr>

## <font color= #6B6B6B> 4.1 Michael Burry's Activity </font>

In [14]:
datan = data.readData(filepath, "Michael Burry")
superInvestor, dates = functions.dataWrangling(datan)

datan.head(10)

,History,Stock,Activity,Share change,% change to portfolio
0,Q4 2021,NaN,NaN,NaN,NaN
1,≡,CXW - CoreCivic Inc.,Add 34.77%,143301.0,1.92
2,≡,BMY - Bristol-Myers Squibb,Buy,300000.0,25.12
3,≡,FNF - Fidelity National Financial Inc.,Buy,325000.0,22.78
4,≡,GD - General Dynamics,Buy,80000.0,22.40
5,≡,IMPX - Aea Bridges Impact Corp Cl A,Buy,1000100.0,13.42
6,≡,GEO - GEO Group Inc.,Reduce 26.65%,308820.0,3.22
7,≡,CVS - CVS Health Corp.,Sell 100.00%,200000.0,40.68
8,≡,LMT - Lockheed Martin Corp.,Sell 100.00%,30000.0,24.82
9,≡,DNOW - NOW Inc.,Sell 100.00%,150000.0,2.75

In [15]:
datan.tail(10)

,History,Stock,Activity,Share change,% change to portfolio
228,≡,FPH - Five Point Holdings LLC,Reduce 6.44%,85245.0,0.63
229,≡,DIS - Walt Disney Co.,Reduce 12.50%,10000.0,1.13
230,≡,CPLG - CorePoint Lodging Inc.,Reduce 27.34%,247384.0,2.81
231,≡,CLF - Cleveland-Cliffs Inc.,Reduce 28.02%,291934.0,2.97
232,≡,FB - Meta Platforms Inc.,Reduce 30.77%,20000.0,3.40
233,≡,ALEX - Alexander & Baldwin,Sell 100.00%,500356.0,8.88
234,≡,MCK - McKesson Corp.,Sell 100.00%,40000.0,4.27
235,≡,BIIB - Biogen Inc.,Sell 100.00%,10000.0,2.91
236,≡,CELG - Celgene Corp.,Sell 100.00%,45000.0,2.79
237,≡,MHK - Mohawk Industries,Sell 100.00%,18809.0,2.13

## <font color= #6B6B6B> 4.2 Michael Burry's Shameless Cloning </font>

In [16]:
cloning = functions.superInvestorCloning(superInvestor, dates)
cloning

1 Failed download:
- NVTRQ: No data found, symbol may be delisted

1 Failed download:
- MIK: No data found, symbol may be delisted

1 Failed download:
- MSGN: No data found, symbol may be delisted

1 Failed download:
- VYGG-WS: No data found, symbol may be delisted

,Ticker,Timestamp (Buy),Buy Price,Timestamp (Sell),Sell Price,Effective Return %,CAGR %
0,JD,2019-05-15 00:00:00,30.440001,2019-08-14 00:00:00,29.629999,-2.660977,-10.120056
1,GSKY,2019-05-15 00:00:00,11.56,2019-11-14 00:00:00,7.74,-33.044987,-54.576748
2,PETQ,2019-05-15 00:00:00,29.370001,2019-08-14 00:00:00,32.16,9.499486,43.191064
3,FDX,2019-08-14 00:00:00,149.869278,2019-11-14 00:00:00,152.036224,1.445891,5.778089
4,GOOG,2019-08-14 00:00:00,1164.290039,2020-05-15 00:00:00,1373.189941,17.942256,24.114294
5,CAH,2019-08-14 00:00:00,38.603271,2019-11-14 00:00:00,50.344688,30.415601,182.676385
6,BABA,2019-08-14 00:00:00,162.059998,2019-11-14 00:00:00,182.800003,12.797733,60.196722
7,GME,2019-11-14 00:00:00,5.98,2021-02-14 00:00:00,49.509998,727.926391,426.702705
8,BBBY,2019-11-14 00:00:00,13.355489,2020-02-14 00:00:00,10.931556,-18.14934,-54.327789
9,CNQ,2019-11-14 00:00:00,24.125399,2020-02-14 00:00:00,25.747089,6.721923,28.990502
10,MAXR,2020-02-14 00:00:00,19.073217,2020-11-14 00:00:00,25.12365,31.722137,43.620324
11,QRVO,2020-02-14 00:00:00,106.019997,2021-02-14 00:00:00,177.029999,66.977933,65.580402
12,CVET,2020-02-14 00:00:00,12.73,2020-05-15 00:00:00,12.18,-4.320497,-16.031041
13,CVE,2020-02-14 00:00:00,8.716276,2020-05-15 00:00:00,3.684418,-57.729446,-96.68419
14,BB,2020-02-14 00:00:00,5.83,2020-05-15 00:00:00,4.42,-24.185246,-66.557367
15,JACK,2020-05-15 00:00:00,64.620865,2020-08-14 00:00:00,78.528717,21.522232,116.222962
16,FB,2020-05-15 00:00:00,210.880005,2020-08-14 00:00:00,261.23999,23.880873,133.307621
17,BA,2020-05-15 00:00:00,120.0,2020-08-14 00:00:00,178.080002,48.400002,376.650514
18,DISCA,2020-05-15 00:00:00,20.469999,2021-05-15 00:00:00,33.849998,65.363945,64.228485
19,BBBY,2020-08-14 00:00:00,12.35,2020-11-14 00:00:00,20.540001,66.315792,632.018982
20,TCOM,2020-08-14 00:00:00,28.540001,2021-02-14 00:00:00,38.610001,35.28381,80.628099
21,CPA,2020-08-14 00:00:00,50.110001,2020-11-14 00:00:00,74.639999,48.952302,375.489896
22,HP,2020-08-14 00:00:00,17.727369,2020-11-14 00:00:00,17.729412,0.011523,0.045099
23,UNIT,2020-08-14 00:00:00,8.941967,2021-05-15 00:00:00,10.251481,14.644586,19.669304
24,ROIC,2020-08-14 00:00:00,11.611731,2021-02-14 00:00:00,15.129258,30.29288,67.820424
25,DBI,2020-08-14 00:00:00,7.3,2021-05-15 00:00:00,20.09,175.205474,278.139132
26,PDS,2020-08-14 00:00:00,15.8,2021-02-14 00:00:00,24.08,52.405061,128.05641
27,KBAL,2020-08-14 00:00:00,11.276829,2021-05-15 00:00:00,13.000343,15.283681,20.54656
28,FB,2020-11-14 00:00:00,278.959991,2021-02-14 00:00:00,273.970001,-1.788783,-6.819292
29,WDC,2020-11-14 00:00:00,43.580002,2021-05-15 00:00:00,76.419998,75.355656,203.723701
30,CVS,2020-11-14 00:00:00,71.272301,2021-02-14 00:00:00,68.877907,-3.359501,-12.516297
31,ALL,2020-11-14 00:00:00,95.027237,2021-05-15 00:00:00,136.424042,43.563094,104.472134
32,LUMN,2020-11-14 00:00:00,9.12068,2021-08-14 00:00:00,12.06,32.22699,44.538174
33,QRTEA,2020-11-14 00:00:00,7.147753,2021-05-15 00:00:00,11.200705,56.702462,143.144394
34,MO,2020-11-14 00:00:00,37.83313,2021-02-14 00:00:00,40.40398,6.795236,29.337584
35,RPT,2020-11-14 00:00:00,6.839447,2021-08-14 00:00:00,12.364844,80.787206,118.334433
36,UBA,2020-11-14 00:00:00,11.655602,2021-08-14 00:00:00,18.724775,60.650429,86.849784
37,LILA,2020-11-14 00:00:00,11.7,2021-02-14 00:00:00,11.93,1.965816,7.915349
38,DNOW,2021-02-14 00:00:00,10.79,2021-08-14 00:00:00,7.3,-32.344762,-54.029632
39,WFC,2021-02-14 00:00:00,34.276993,2021-05-15 00:00:00,47.296627,37.983595,262.501516
40,GEO,2021-02-14 00:00:00,8.6,2021-05-15 00:00:00,6.33,-26.395353,-70.649133
41,TAP,2021-02-14 00:00:00,43.837704,2021-05-15 00:00:00,57.067825,30.179778,187.193168
42,CXW,2021-02-14 00:00:00,7.62,2022-02-19 20:30:01.062076,9.87,29.527559,28.624994
43,HFC,2021-02-14 00:00:00,33.046104,2021-05-15 00:00:00,36.669998,10.966175,51.622087
44,IMKTA,2021-02-14 00:00:00,50.036034,2021-08-14 00:00:00,64.330002,28.567349,64.837308
45,SXC,2021-02-14 00:00:00,5.997978,2021-11-14 00:00:00,6.438521,7.34487,9.797061
46,ARCC,2021-02-14 00:00:00,16.514635,2021-05-15 00:00:00,18.658438,12.981229,62.939051
47,ZYME,2021-05-15 00:00:00,29.73,2021-08-14 00:00:00,32.0,7.635387,33.787545
48,CVS,2021-05-15 00:00:00,83.121117,2022-02-14 00:00:00,103.0,23.915563,32.406776
49,TBT,2021-05-15 00:00:00,21.17,2021-08-14 00:00:00,17.42,-17.713746,-53.758592
50,OXY,2021-05-15 00:00:00,26.361799,2021-08-14 00:00:00,24.771996,-6.03071,-21.813601
51,RKLB,2021-05-15 00:00:00,10.0,2021-08-14 00:00:00,10.21,2.1,8.5691
52,HP,2021-05-15 00:00:00,29.892401,2021-08-14 00:00:00,25.784954,-13.740772,-44.27578
53,PDS,2021-05-15 00:00:00,29.32,2021-08-14 00:00:00,30.34,3.478856,14.486334
54,MRNS,2021-05-15 00:00:00,15.03,2021-11-14 00:00:00,12.53,-16.6334,-30.084318
55,MDP,2021-05-15 00:00:00,59.07,2021-08-14 00:00:00,NaN,NaN,NaN
56,GNK,2021-05-15 00:00:00,15.160028,2021-08-14 00:00:00,17.582441,15.978954,79.757449
57,GOGL,2021-05-15 00:00:00,7.643457,2021-11-14 00:00:00,8.5,11.206219,23.238307
58,STNG,2021-05-15 00:00:00,20.597227,2021-11-14 00:00:00,16.557749,-19.611758,-34.913112
59,AADI,2021-05-15 00:00:00,1.66,2021-08-14 00:00:00,2.06,24.096385,134.917427
60,DISCK,2021-08-14 00:00:00,26.83,2021-11-14 00:00:00,27.190001,1.341784,5.353951
61,OVV,2021-08-14 00:00:00,23.279959,2021-11-14 00:00:00,35.756493,53.593454,436.147767
62,GEO,2021-08-14 00:00:00,8.48,2022-02-19 20:30:02.649586,6.54,-22.877355,-39.031092
63,VYGG,2021-08-14 00:00:00,9.71,2021-11-14 00:00:00,9.89,1.853762,7.452034
64,LMT,2021-11-14 00:00:00,338.122559,2022-02-14 00:00:00,386.970001,14.446668,69.557374
65,DNOW,2021-11-14 00:00:00,9.87,2022-02-14 00:00:00,9.3,-5.775073,-20.766345
66,SCYX,2021-11-14 00:00:00,6.75,2022-02-14 00:00:00,4.54,-32.740741,-78.817053
67,BMY,2022-02-14 00:00:00,66.809998,2022-02-19 20:30:04.147489,67.550003,1.107627,121.025321
68,FNF,2022-02-14 00:00:00,47.799999,2022-02-19 20:30:05.981387,47.75,-0.104601,-7.258309
69,GD,2022-02-14 00:00:00,211.169998,2022-02-19 20:30:07.505764,215.820007,2.202022,379.825195
70,IMPX,2022-02-14 00:00:00,9.93,2022-02-19 20:30:09.453325,9.93,0.0,0.0

## <font color= #6B6B6B> 4.3 Michael Burry's Shameless Cloning Performance </font>

In [17]:
functions.metrics(cloning)

   Mean Effective Return % Mean CAGR %  Mean Holding Period (Years)
0                26.319408  -10.120056                     0.404969

## <font color= #6B6B6B> 4.4 Comments </font>

In the case of Michael Burry, good returns are obtained by cloning his trades. Although it is clarified that the CAGR may not be a very suitable metric, since the average investment period of Burry is only a few months.

<br>

# <font color= #6B6B6B> 5. Conclusions </font>

<hr style="border:0.02in solid gray"> </hr>

Value investing is something that will never go out of style, since through this philosophy stocks are seen as part of a business, so before pulling the trigger, value investors should do a thorough analysis to put the odds in their favor. Even with the delay of the information, it is verified that cloning the trades of these superinvestors generates good returns.

<br>

# <font color= #6B6B6B> <font size = 6> 6. References </font>

<hr style="border:0.02in solid gray"> </hr>

+ DATORAMA. (2022). Invest Alongside Superinvestors. February, 2022, from DATORAMA. Web site: https://www.dataroma.com/m/home.php

<br>